### ISSUE TITLE
elasticsearch exited with code 137

### ISSUE THREAD

**Issue by gie3d** [gnokoheat/elk-with-filebeat-by-docker-compose#1]
First of all, many thanks for making this! 🥳

I cloned the project and run `docker-compose up` everything seems to be ok until I found the error message:

```
elasticsearch exited with code 137
```

I did a quick research and found that it might relate to memory and look at the `docker-compose.yml` and seems like (if I understand correctly) that you set the maximum memory of elasticsearch to 512mb. 

So I wonder if you faced the issue as I described above? and if you could share idea about this problem.

again, thank you very much for making this 👏

**Comment by gnokoheat** [comment]
@gie3d hello😊
When using elasticsearch, always be careful of memory issues.
This code provided just sample code.
In addition, it is operated with only one node.
In production environment, it is essential to operate with multiple nodes and optimize these settings.
It is recommended to set the jvm memory options according to the environment in use.

**Comment by gie3d** [comment]
Many thanks 🔥  give more memory to docker resource does the trick
