### ISSUE TITLE
Getting the following issue.

### ISSUE THREAD

**Issue by PankajVP** [gnokoheat/elk-with-filebeat-by-docker-compose#3]
➜  elk-with-filebeat-by-docker-compose git:(master) docker-compose up -d

[+] Running 2/11
 ✘ kibana Error                                                                                                                   2.4s
 ⠼ logstash Pulling                                                                                                               2.4s
 ✘ elasticsearch Error                                                                                                            2.4s
 ⠼ filebeat 7 layers [⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                            2.4s
   ⠼ c808caf183b6 Pulling fs layer                                                                                                0.4s
   ⠼ 0ad724d0d2e4 Pulling fs layer                                                                                                0.4s
   ⠼ 96c1ebfd2ab2 Pulling fs layer                                                                                                0.4s
   ⠼ 96df637ea680 Waiting                                                                                                         0.4s
   ⠼ 77792ec475bc Waiting                                                                                                         0.4s
   ⠼ c68751b9be58 Waiting                                                                                                         0.4s
   ⠼ 967522c87331 Waiting                                                                                                         0.4s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by gnokoheat** [comment]
@PankajVP Hello!
The reason is that there is no ARM-based Docker image for the 7.5.0 version you attempted.
I will soon update it to include an ARM-based Docker image.
