### ISSUE TITLE
Logstash error

### ISSUE THREAD

**Issue by JohnatanT** [gnokoheat/elk-with-filebeat-by-docker-compose#5]
Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ClientProtocolException] elasticsearch:9200 failed to respond"}

**Comment by JohnatanT** [comment]
Version 8.12.1

**Comment by gnokoheat** [comment]
@JohnatanT Hello

This config is written for version 7.x. Version 8.x has not been tested. Please use version 7.17.18 as it is in the code.
